### ISSUE TITLE
Alarms sensors are always 0

### ISSUE THREAD

**Issue by IvanMazzoli** [roleoroleo/4-noks_ha_integration#2]
I've configured seven devices of Elios4you through your integration and all the sensors are working perfectly but the alarms.
When we trigger an alarm in the solar system (eg. we trip the inverter) the Elios module sends us a mail via 4cloud that tells us that the Alarm 1 has been triggered. 
On the other hand, HomeAssistant always shows the value 0 for alarm_1, alarm_2 and power_alarm. I've also checked if the rel_warning or relay_state would change state but nothing happens.

Can you also tell me what is the polling time for the sensors?

Thanks

**Comment by roleoroleo** [comment]
Polling time is 60 s.
In this moment I don't have the device, so it's not easy to help you.
Are you able to capture the network traffic between ha and your device?
I would like to read the content of the packets when an alarm is fired.

**Comment by IvanMazzoli** [comment]
> Are you able to capture the network traffic between ha and your device?

For that I need to check with my ICT department, the whole office is on vacation until Monday.

Now I've tried to stop HA so I could connect to the device with Putty via telnet and @dat replied with all the sensor values, but I don't see any difference with the alarm tripped or not tripped. I'm starting to belive that this value it's not readable with the @dat command, could it be that another command is needed to "read" the inputs of the device?

**Comment by roleoroleo** [comment]
> Now I've tried to stop HA so I could connect to the device with Putty via telnet and @dat replied with all the sensor values, but I don't see any difference with the alarm tripped or not tripped. I'm starting to belive that this value it's not readable with the @dat command

I think you are right.

> could it be that another command is needed to "read" the inputs of the device?

Yes, maybe. This is why I asked you for a capture.

**Comment by IvanMazzoli** [comment]
I've checked with our electrician and we found out we had them wired incorrectly - on all 5 of them.
We then proceded to test each one individually and it works like a charme!

**Comment by roleoroleo** [comment]
Good.
Thank you for your feedback.
