### ISSUE TITLE
problem update

### ISSUE THREAD

**Issue by Minoksse** [roleoroleo/4-noks_ha_integration#3]
hi ! I've got serious problem with 4-NOKS Elios4you integration since my update "Home Assistant Core 2023.4.6" >>> "Home Assistant Core 2023.5.2" I've got 0 entities UP :/ 

am I the only one with this problem?

thx

**Comment by Minoksse** [comment]
Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:597 
Integration: Capteur (documentation, issues) 
First occurred: 14 mai 2023 à 21:39:27 (2 occurrences) 
Last logged: 16:14:11

Sensor sensor.4_noks_xx_utc_time has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: 14/05/2023 19:41:11 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.
Sensor sensor.4_noks_xx_utc_time has device class None, state class None and unit thus indicating it has a numeric value; however, it has the non-numeric value: 15/05/2023 14:15:57 (<class 'str'>); Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by roleoroleo** [comment]
Please, try release 0.0.3

**Comment by Minoksse** [comment]
wow thx works fine :)
