### ISSUE TITLE
Unable to get configuration

### ISSUE THREAD

**Issue by Donez84** [roleoroleo/4-noks_ha_integration#5]
Good morning,
 sorry to bother you. I installed the component in HA but when I enter the ip address I get an error: Unable to get configuration.
HA is in the same network as 4-NOKS and from a pc I can connect to 4-NOKS via telnet on port 5001. With nmap I get port 5001/tcp open commplex-link open.
Is there anything else I can do to solve the problem?

**Comment by Donez84** [comment]
![image](https://github.com/roleoroleo/4-noks_ha_integration/assets/64431438/7415d512-7bb2-41d1-80af-da468d51718e)

**Comment by roleoroleo** [comment]
Please, check the log in ha.
